// <auto-generated />
using CadastroCarrosAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CadastroCarrosAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250609193414_AdicionarDadosIniciaisDeCarros")]
    partial class AdicionarDadosIniciaisDeCarros
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("CadastroCarrosAPI.Models.Carro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Carros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ano = 1978,
                            Marca = "Volkswagen",
                            Modelo = "Fusca",
                            Placa = "ABC-1234"
                        },
                        new
                        {
                            Id = 2,
                            Ano = 2010,
                            Marca = "Fiat",
                            Modelo = "Uno",
                            Placa = "DEF-5678"
                        },
                        new
                        {
                            Id = 3,
                            Ano = 2020,
                            Marca = "Chevrolet",
                            Modelo = "Onix",
                            Placa = "GHI-9012"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
